version: '3.4'
services:
  thumbor:
    image: minimalcompact/thumbor
    ports:
      - 9999:80

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hana
      POSTGRES_USER: hana
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
